export default {
  SIGN_UP_ACTION: 'SIGN_UP_ACTION',
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_RESPONSE: 'SIGN_UP_RESPONSE',
  SIGN_UP_ERROR: 'SIGN_UP_RESPONSE',

  LOGIN_ACTION: 'LOGIN_ACTION',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_RESPONSE: 'LOGIN_RESPONSE',
  LOGIN_ERROR: 'LOGIN_RESPONSE',

  REFRESH_ACTION: 'REFRESH_ACTION',
  REFRESH_REQUEST: 'REFRESH_REQUEST',
  REFRESH_RESPONSE: 'REFRESH_RESPONSE',
  REFRESH_ERROR: 'REFRESH_RESPONSE',

  LOGOUT_ACTION: 'LOGOUT_ACTION',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_ERROR: 'LOGOUT_ERROR',
  LOGOUT_RESPONSE: 'LOGOUT_RESPONSE',

  GET_USERS_ACTION: 'GET_USERS_ACTION',
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_ERROR: 'GET_USERS_ERROR',
  GET_USERS_RESPONSE: 'GET_USERS_RESPONSE',

  SWITCH_USER_STATUS_ACTION: 'SWITCH_USER_STATUS_ACTION',
  SWITCH_USER_STATUS_REQUEST: 'SWITCH_USER_STATUS_REQUEST',
  SWITCH_USER_STATUS_ERROR: 'SWITCH_USER_STATUS_ERROR',
  SWITCH_USER_STATUS_RESPONSE: 'SWITCH_USER_STATUS_RESPONSE',

  GET_USER_DATA_ACTION: 'GET_USER_DATA_ACTION',
  GET_USER_DATA_REQUEST: 'GET_USER_DATA_REQUEST',
  GET_USER_DATA_ERROR: 'GET_USER_DATA_ERROR',
  GET_USER_DATA_RESPONSE: 'GET_USER_DATA_RESPONSE',

  UPDATE_USER_FULL_NAME_ACTION: 'UPDATE_USER_FULL_NAME_ACTION',
  UPDATE_USER_FULL_NAME_REQUEST: 'UPDATE_USER_FULL_NAME_REQUEST',
  UPDATE_USER_FULL_NAME_ERROR: 'UPDATE_USER_FULL_NAME_ERROR',
  UPDATE_USER_FULL_NAME_RESPONSE: 'UPDATE_USER_FULL_NAME_RESPONSE',

  UPDATE_USER_ABOUT_ME_ACTION: 'UPDATE_USER_ABOUT_ME_ACTION',
  UPDATE_USER_ABOUT_ME_REQUEST: 'UPDATE_USER_ABOUT_ME_REQUEST',
  UPDATE_USER_ABOUT_ME_ERROR: 'UPDATE_USER_ABOUT_ME_ERROR',
  UPDATE_USER_ABOUT_ME_RESPONSE: 'UPDATE_USER_ABOUT_ME_RESPONSE',

  UPLOAD_USER_PHOTO_ACTION: 'UPLOAD_USER_PHOTO_ACTION',
  UPLOAD_USER_PHOTO_REQUEST: 'UPLOAD_USER_PHOTO_REQUEST',
  UPLOAD_USER_PHOTO_ERROR: 'UPLOAD_USER_PHOTO_ERROR',
  UPLOAD_USER_PHOTO_RESPONSE: 'UPLOAD_USER_PHOTO_RESPONSE',

  UPDATE_USER_PASSWORD_ACTION: 'UPDATE_USER_PASSWORD_ACTION',
  UPDATE_USER_PASSWORD_REQUEST: 'UPDATE_USER_PASSWORD_REQUEST',
  UPDATE_USER_PASSWORD_ERROR: 'UPDATE_USER_PASSWORD_ERROR',
  UPDATE_USER_PASSWORD_RESPONSE: 'UPDATE_USER_PASSWORD_RESPONSE',

};
