export default {
  SIGN_UP_ACTION: 'SIGN_UP_ACTION',
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_RESPONSE: 'SIGN_UP_RESPONSE',
  SIGN_UP_ERROR: 'SIGN_UP_RESPONSE',

  LOGIN_ACTION: 'LOGIN_ACTION',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_RESPONSE: 'LOGIN_RESPONSE',
  LOGIN_ERROR: 'LOGIN_RESPONSE',

  REFRESH_ACTION: 'REFRESH_ACTION',
  REFRESH_REQUEST: 'REFRESH_REQUEST',
  REFRESH_RESPONSE: 'REFRESH_RESPONSE',
  REFRESH_ERROR: 'REFRESH_RESPONSE',

  LOGOUT_ACTION: 'LOGOUT_ACTION',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_ERROR: 'LOGOUT_ERROR',
  LOGOUT_RESPONSE: 'LOGOUT_RESPONSE',

  GET_USERS_ACTION: 'GET_USERS_ACTION',
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_ERROR: 'GET_USERS_ERROR',
  GET_USERS_RESPONSE: 'GET_USERS_RESPONSE',

  SWITCH_USER_STATUS_ACTION: 'SWITCH_USER_STATUS_ACTION',
  SWITCH_USER_STATUS_REQUEST: 'SWITCH_USER_STATUS_REQUEST',
  SWITCH_USER_STATUS_ERROR: 'SWITCH_USER_STATUS_ERROR',
  SWITCH_USER_STATUS_RESPONSE: 'SWITCH_USER_STATUS_RESPONSE',
};
